export const GET_MODAL_DATA_SUCCESS = 'GET_MODAL_DATA_SUCCESS';
export const GET_MODAL_DATA_FAILURE = 'GET_MODAL_DATA_FAILURE';
export const GET_MODAL_DATA_STARTED = 'GET_MODAL_DATA_STARTED';
export const SET_IS_OPEN_MODAL = 'SET_IS_OPEN_MODAL';